from enum import Enum

DEFAULT_PORT = 1357
MAX_CONNECTIONS = 50
MAX_BUFFER_SIZE = 4096
REQUEST_HEADER_SIZE = 23
LOCALHOST = "127.0.0.1"
CLIENT_ID_SIZE = 16
VERSION_SIZE = 1
SERVER_VERSION = 2
CLIENT_VERSION = 1
CODE_SIZE = 2
PAYLOAD_SIZE = 4
USER_NAME_SIZE = 255
PUBLIC_KEY_SIZE = 160
MESSAGE_TYPE_SIZE = 1
MESSAGE_ID_SIZE = 4
CONTENT_SIZE = 4
REQUEST_HEADER_SIZE = CLIENT_ID_SIZE + VERSION_SIZE + CODE_SIZE + PAYLOAD_SIZE
RESPONSE_HEADER_SIZE = VERSION_SIZE + CODE_SIZE + PAYLOAD_SIZE
ZERO_CHAR = '\0'


class Response_Code(Enum):
    REGISTER_SUCCEEDED = 2100,
    CLIENT_LIST = 2101,
    PUBLIC_KEY = 2102,
    MESSAGE_SENT = 2103,
    WAITING_MESSAGES = 2104,
    GENERAL_ERROR = 9000

class RequestCode(Enum):
    REGISTER = 600, "Register a new client"
    GET_CLIENT_LIST = 601, "Get the list of clients"
    GET_PUBLIC_KEY = 602, "Get the public key of a client"
    MESSAGE = 603, "Send a message to a client"
    GET_WAITING_MESSAGES = 604, "Get waiting messages for a client"


class Message_Type(Enum):
    GET_SYM_KEY = 1
    SEND_SYM_KEY = 2
    SEND_TEXT_MESSAGE = 3
    SEND_FILE = 4

